# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:5.1.0"
  amd64: "ghcr.io/home-assistant/amd64-base:5.1.0"
  armhf: "ghcr.io/home-assistant/armhf-base:5.1.0"
  armv7: "ghcr.io/home-assistant/armv7-base:5.1.0"
  i386: "ghcr.io/home-assistant/i386-base:5.1.0"
labels:
  org.opencontainers.image.title: "Add-on for Elastic Universal Profiling"
  org.opencontainers.image.description: "Add-on for Elastic Universal Profiling"
  org.opencontainers.image.source: "https://github.com/strawgate/ha-addon-elastic-universal-profiling"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
