# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Elastic Universal Profiling
version: "0.1.0"
slug: ha-addon-es-universal-profiling
description: Elastic Universal Profiling add-on
url: "https://github.com/strawgate/ha-addon-elastic-universal-profiling"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: false
full_access: true
options:
  projectid: 1
  secrettoken: "secret token"
  collectionagent: "url"
schema:
  projectid: "int"
  secrettoken: "str"
  collectionagent: "str"
image: "ghcr.io/strawgate/ha-addon-elastic-universal-profiling-{arch}"