# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Elastic Universal Profiling
version: "0.1.0"
slug: es-universal-profiling
description: Elastic Universal Profiling add-on
url: "https://github.com/strawgate/ha-addon-elastic-universal-profiling"
arch:
  - aarch64
  - amd64
init: false
apparmor: false
full_access: true
host_pid: true
privileged:
  - BPF
  - SYS_ADMIN
  - SYS_RESOURCE
docker_api: true
kernel_modules: true
options:
  projectid: 1
  secrettoken: "secret token"
  collectionagent: "url"
schema:
  projectid: "int"
  secrettoken: "str"
  collectionagent: "str"
image: "ghcr.io/strawgate/ha-addon-elastic-universal-profiling-{arch}"